#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

/**
 * GeoWE Forge CLI v1.0.1
 */

const version = "1.0.1";
const args = process.argv.slice(2);

if (args.includes('--version') || args.includes('-v')) {
    console.log(`GeoWE Forge CLI v${version}`);
    process.exit(0);
}

// Comando INIT
if (args[0] === 'init') {
    const targetDir = args[1] || '.';
    const targetPath = path.resolve(targetDir);

    if (!fs.existsSync(targetPath)) {
        fs.mkdirSync(targetPath, { recursive: true });
    }

    const pluginId = path.basename(targetPath) === '.' ? 'mi-plugin-geowe' : path.basename(targetPath);

    const manifest = {
        id: pluginId,
        name: pluginId.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' '),
        version: "1.0.0",
        main: "index.js",
        icon: "extension",
        description: "Mi nueva herramienta para GeoWE Studio"
    };

    const pkgJson = {
        name: pluginId,
        version: "1.0.0",
        private: true,
        dependencies: {
            "jszip": "^3.10.1"
        }
    };

    const indexJs = `export default {
  id: '${pluginId}',
  
  activate: (context) => {
    console.log('Plugin "${manifest.name}" activado');
    context.ui.setStatus('¡Hola desde ${manifest.name}!');

    context.ui.addButton({
      id: 'btn-hello',
      label: 'Saludar',
      icon: 'mood',
      commandId: 'say.hello'
    });

    context.commands.register('say.hello', () => {
      context.ui.addModal({
        id: 'hello-modal',
        title: 'Geowe Studio',
        content: '<div style="padding:20px"><h3>¡Bienvenido!</h3><p>Este plugin ha sido generado con <b>GeoWE Forge</b>.</p></div>'
      });
    });
  },

  deactivate: () => {
    console.log('Plugin desactivado');
  }
};`;

    const sdkTypes = `/**
 * GeoWE Studio SDK - Autogenerated Definition
 */
export interface PluginContext {
  map: any;
  layers: any;
  ui: any;
  commands: any;
  events: any;
}
export interface GeoWEPlugin {
  id: string;
  name: string;
  activate: (ctx: any) => void;
  deactivate: () => void;
}`;

    fs.writeFileSync(path.join(targetPath, 'manifest.json'), JSON.stringify(manifest, null, 2));
    fs.writeFileSync(path.join(targetPath, 'package.json'), JSON.stringify(pkgJson, null, 2));
    fs.writeFileSync(path.join(targetPath, 'index.js'), indexJs);
    fs.writeFileSync(path.join(targetPath, 'geowe-studio.d.ts'), sdkTypes);
    
    // Inyectar una copia del propio script para empaquetado autónomo
    const currentScript = fs.readFileSync(__filename, 'utf8');
    fs.writeFileSync(path.join(targetPath, 'forge.js'), currentScript);

    console.log(`
    ✨ Proyecto inicializado con éxito en: ${targetPath}
    
    Archivos creados:
    - package.json (Dependencias)
    - manifest.json (Configuración)
    - index.js (Lógica principal)
    - geowe-studio.d.ts (Interfaces para IntelliSense)
    - forge.js (Herramienta de empaquetado autónoma)
    
    ¡Listo para empezar! 
    1. Ejecuta 'npm install' para instalar las herramientas de empaquetado.
    2. Prueba a arrastrar index.js a GeoWE Studio para verlo en acción.
    `);
    process.exit(0);
}

const pluginPath = args[0];

if (!pluginPath || args.includes('--help') || args.includes('-h')) {
    console.log(`
    📦 GeoWE Forge CLI v${version}
    
    Uso: 
    geowe-forge init <ruta>      Inicializa un nuevo proyecto de plugin
    geowe-forge <ruta>           Empaqueta un proyecto existente (.gplugin, .gext, .gapp)
    `);
    process.exit(0);
}

// Carga tardía de JSZip para evitar errores en el comando 'init' sin node_modules
let JSZip;
try {
    JSZip = require('jszip');
} catch (e) {
    console.error(`
    ❌ Error: No se encontró el módulo 'jszip'.
    Para empaquetar plugins es necesario instalar las dependencias.
    Por favor, ejecuta: npm install jszip
    `);
    process.exit(1);
}

const absolutePath = path.resolve(pluginPath);

if (!fs.existsSync(absolutePath)) {
    console.error(`❌ Error: La ruta '${pluginPath}' no existe.`);
    process.exit(1);
}

const manifestPath = path.join(absolutePath, 'manifest.json');
const extensionPath = path.join(absolutePath, 'extension.json');
const appPath = path.join(absolutePath, 'app.json');

let manifest;
let type = 'plugin';

if (fs.existsSync(appPath)) {
    manifest = JSON.parse(fs.readFileSync(appPath, 'utf8'));
    type = 'app';
} else if (fs.existsSync(extensionPath)) {
    manifest = JSON.parse(fs.readFileSync(extensionPath, 'utf8'));
    type = 'extension';
} else if (fs.existsSync(manifestPath)) {
    manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
} else {
    console.error(`❌ Error: No se encontró app.json, extension.json ni manifest.json en ${absolutePath}`);
    process.exit(1);
}

const zip = new JSZip();

function addFilesToZip(dir, zipInstance, rootDir) {
    const items = fs.readdirSync(dir);
    
    items.forEach(item => {
        const fullPath = path.join(dir, item);
        const stats = fs.statSync(fullPath);
        
        // Excluir node_modules y archivos ocultos
        if (item === 'node_modules' || item.startsWith('.')) return;

        if (stats.isDirectory()) {
            const folder = zipInstance.folder(item);
            addFilesToZip(fullPath, folder, rootDir);
        } else {
            const content = fs.readFileSync(fullPath);
            zipInstance.file(item, content);
        }
    });
}

console.log(`📦 Empaquetando ${type}: ${manifest.name} (${manifest.id})...`);

addFilesToZip(absolutePath, zip, absolutePath);

const typeToExt = {
    'app': 'gapp',
    'extension': 'gext',
    'plugin': 'gplugin'
};

const ext = typeToExt[type];
const outputFileName = `${manifest.id}_v${manifest.version || '1.0.0'}.${ext}`;
const outputPath = path.join(process.cwd(), outputFileName);

zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })
    .then(buffer => {
        fs.writeFileSync(outputPath, buffer);
        console.log(`✅ ¡Éxito! Paquete generado en: ${outputPath}`);
    })
    .catch(err => {
        console.error('❌ Error al generar el ZIP:', err);
        process.exit(1);
    });
